import { createHmac, timingSafeEqual } from "node:crypto";
import net from "node:net";

export const protocolVersion: 3 = 3;

export type JsonValue =
  null | boolean | number | string | JsonValue[] | JsonObject;
export type JsonObject = { [key: string]: JsonValue };
export type BridgeEndpoint =
  { type: "unix"; path: string } | { type: "tcp"; host: string; port: number };
export interface BridgeCredential {
  id: string;
  secret: Uint8Array;
}
export type BridgeProtocolStatus =
  | "ok"
  | "busy"
  | "not-found"
  | "request-conflict"
  | "invalid-state"
  | "failed"
  | "version-mismatch";
export type TimingPolicy =
  | { kind: "absolute"; at: number }
  | { kind: "no-progress"; timeoutMs: number }
  | { kind: "phase"; timeoutMs: number };
export interface RequestTimingPolicy {
  connect: TimingPolicy;
  challenge: TimingPolicy;
  requestWrite: TimingPolicy;
  response: TimingPolicy;
}
export interface BridgeProtocolRequest {
  endpoint: BridgeEndpoint;
  credential: BridgeCredential;
  requestId: string;
  operation: string;
  payload: JsonObject;
  timing: RequestTimingPolicy;
  signal: AbortSignal;
}
export interface BridgeProtocolResponse {
  status: BridgeProtocolStatus;
  payload: JsonValue;
}
export interface StreamTimingPolicy extends RequestTimingPolicy {
  stream: TimingPolicy;
  end: TimingPolicy;
}
export interface BridgeProtocolStreamRequestBase extends Omit<
  BridgeProtocolRequest,
  "timing"
> {
  timing: StreamTimingPolicy;
}
export interface BinaryStreamRequest extends BridgeProtocolStreamRequestBase {
  kind: "binary";
}
export interface AuthenticatedFrameStreamRequest extends BridgeProtocolStreamRequestBase {
  kind: "authenticated-frames";
}
export interface BinaryStreamContext {
  metadata: JsonValue;
  bytes: { readExactly(length: number): AsyncIterable<Uint8Array> };
}
export interface AuthenticatedFrameStreamContext {
  metadata: JsonValue;
  frames: AsyncIterable<JsonValue>;
}
export type BridgeProtocolStreamResponse<T> =
  | { status: "ok"; payload: JsonValue; value: T }
  | {
      status: Exclude<BridgeProtocolStatus, "ok">;
      payload: JsonValue;
    };
export type BridgeProtocolFailureKind =
  "transport" | "deadline" | "cancelled" | "malformed" | "authentication";
export type BridgeProtocolFailureStage =
  "connect" | "challenge" | "request-write" | "response" | "stream";

type StreamRequest = BinaryStreamRequest | AuthenticatedFrameStreamRequest;

const MAX_FRAME_BYTES = 64 * 1024;
const TEST_ADAPTER = Symbol.for("pi-dictation.bridge-protocol.test-adapter");
const STATUSES = new Set([
  "ok",
  "busy",
  "not-found",
  "request-conflict",
  "invalid-state",
  "failed",
  "version-mismatch",
]);
const CANONICAL_IDENTITY =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

// A Bridge identity has one canonical form, and every identity is generated by `randomUUID`, so a
// non-canonical spelling can only come from a hand-written file. Do not normalise one here: the
// companion's `readCredential` rejects a non-canonical identity in its own credential store, and its
// request authentication looks that store up by exact match, so lowercasing a hand-written identity
// would only replace this rejection with an authentication failure against an identity the companion
// does not hold, and would suggest re-spelling the file instead of generating one.
export function isCanonicalIdentity(value: unknown): value is string {
  return typeof value === "string" && CANONICAL_IDENTITY.test(value);
}

export class BridgeProtocolFailure extends Error {
  readonly kind: BridgeProtocolFailureKind;
  readonly stage: BridgeProtocolFailureStage;

  constructor(
    kind: BridgeProtocolFailureKind,
    stage: BridgeProtocolFailureStage,
    cause?: unknown
  ) {
    super(
      `${kind} during ${stage}`,
      cause === undefined ? undefined : { cause }
    );
    this.name = "BridgeProtocolFailure";
    this.kind = kind;
    this.stage = stage;
  }
}

function failure(
  kind: BridgeProtocolFailureKind,
  stage: BridgeProtocolFailureStage,
  cause?: unknown
) {
  return new BridgeProtocolFailure(kind, stage, cause);
}

function protocolCause(code: string, message: string) {
  return Object.assign(new Error(message), { code });
}

function trailingBytesFailure(stage: BridgeProtocolFailureStage) {
  return failure(
    "malformed",
    stage,
    protocolCause("ERR_BRIDGE_TRAILING_BYTES", "unexpected trailing bytes")
  );
}

function frameLengthFailure(stage: BridgeProtocolFailureStage) {
  return failure(
    "malformed",
    stage,
    protocolCause("ERR_BRIDGE_FRAME_LENGTH", "frame length is out of bounds")
  );
}

function encodingFailure(stage: BridgeProtocolFailureStage) {
  return failure(
    "malformed",
    stage,
    protocolCause("ERR_BRIDGE_ENCODING", "noncanonical encoding")
  );
}

function payloadFailure(stage: BridgeProtocolFailureStage, cause: unknown) {
  const message = cause instanceof Error ? cause.message : "unknown";
  return failure(
    "malformed",
    stage,
    protocolCause(
      "ERR_BRIDGE_PAYLOAD",
      `authenticated payload is not strict JSON: ${message}`
    )
  );
}

function versionDataFailure(stage: BridgeProtocolFailureStage) {
  return failure(
    "malformed",
    stage,
    protocolCause(
      "ERR_BRIDGE_VERSION_DATA",
      "authenticated version data is invalid"
    )
  );
}

function exactObject(
  value: unknown,
  keys: readonly string[]
): value is Record<string, unknown> {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Object.keys(value).sort().join("\0") === [...keys].sort().join("\0")
  );
}

function validateJson(
  value: unknown,
  seen: Set<object> = new Set()
): asserts value is JsonValue {
  if (value === null || typeof value === "string" || typeof value === "boolean")
    return;
  if (typeof value === "number") {
    if (Number.isFinite(value)) return;
    throw new TypeError("JSON numbers must be finite");
  }
  if (typeof value !== "object")
    throw new TypeError("payload is not JSON-representable");
  if (seen.has(value)) throw new TypeError("payload must not be cyclic");
  seen.add(value);
  for (
    let prototype: object | null = value;
    prototype;
    prototype = Object.getPrototypeOf(prototype) as object | null
  ) {
    if (Object.getOwnPropertyDescriptor(prototype, "toJSON"))
      throw new TypeError("payload serialization hooks are unsupported");
  }
  if (Array.isArray(value)) {
    for (let index = 0; index < value.length; index += 1) {
      const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
      if (!descriptor) throw new TypeError("payload arrays must not be sparse");
      if (!("value" in descriptor))
        throw new TypeError("payload accessors are unsupported");
      validateJson(descriptor.value, seen);
    }
  } else {
    const prototype: object | null = Object.getPrototypeOf(value) as
      object | null;
    if (prototype !== Object.prototype && prototype !== null)
      throw new TypeError("payload must contain only JSON objects");
    for (const key of Object.keys(value)) {
      const descriptor = Object.getOwnPropertyDescriptor(value, key);
      if (!descriptor || !("value" in descriptor))
        throw new TypeError("payload accessors are unsupported");
      validateJson(descriptor.value, seen);
    }
  }
  seen.delete(value);
}

function strictJson(
  bytes: Uint8Array,
  stage: BridgeProtocolFailureStage = "response"
): JsonValue {
  let text;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch (error) {
    throw failure("malformed", stage, error);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(text) as unknown;
    validateJson(parsed);
  } catch (error) {
    throw failure("malformed", stage, error);
  }
  let index = 0;
  const whitespace = () => {
    while (/\s/.test(text[index] ?? "")) index += 1;
  };
  const string = () => {
    const start = index++;
    while (index < text.length) {
      if (text[index] === "\\") index += 2;
      else if (text[index++] === '"')
        return JSON.parse(text.slice(start, index));
    }
    throw failure("malformed", stage);
  };
  const value = () => {
    whitespace();
    if (text[index] === "{") {
      index += 1;
      whitespace();
      const keys = new Set();
      if (text[index] === "}") {
        index += 1;
        return;
      }
      while (true) {
        if (text[index] !== '"') throw failure("malformed", stage);
        const key = string();
        if (keys.has(key)) throw failure("malformed", stage);
        keys.add(key);
        whitespace();
        if (text[index++] !== ":") throw failure("malformed", stage);
        value();
        whitespace();
        if (text[index] === "}") {
          index += 1;
          return;
        }
        if (text[index++] !== ",") throw failure("malformed", stage);
        whitespace();
      }
    }
    if (text[index] === "[") {
      index += 1;
      whitespace();
      if (text[index] === "]") {
        index += 1;
        return;
      }
      while (true) {
        value();
        whitespace();
        if (text[index] === "]") {
          index += 1;
          return;
        }
        if (text[index++] !== ",") throw failure("malformed", stage);
      }
    }
    if (text[index] === '"') {
      string();
      return;
    }
    const start = index;
    while (index < text.length && !/[\s,}\]]/.test(text[index])) index += 1;
    if (index === start) throw failure("malformed", stage);
  };
  value();
  whitespace();
  if (index !== text.length) throw failure("malformed", stage);
  return parsed;
}

function canonicalBase64(
  value: unknown,
  expectedBytes?: number,
  stage: BridgeProtocolFailureStage = "response"
) {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.length % 4 !== 0 ||
    !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(
      value
    )
  ) {
    throw encodingFailure(stage);
  }
  const decoded = Buffer.from(value, "base64");
  if (
    decoded.toString("base64") !== value ||
    (expectedBytes !== undefined && decoded.length !== expectedBytes)
  ) {
    throw encodingFailure(stage);
  }
  return decoded;
}

function canonicalHex(
  value: unknown,
  expectedBytes: number,
  stage: BridgeProtocolFailureStage = "response"
) {
  if (
    typeof value !== "string" ||
    value.length !== expectedBytes * 2 ||
    !/^[0-9a-f]+$/.test(value)
  ) {
    throw failure(
      "authentication",
      stage,
      protocolCause("ERR_BRIDGE_ENCODING", "noncanonical hexadecimal")
    );
  }
  return Buffer.from(value, "hex");
}

type AuthenticationField = string | number | Uint8Array;

function authEncoding(fields: readonly AuthenticationField[]): Buffer {
  const pieces = [Buffer.from("pi-dictation-bridge-auth-v1\0")];
  for (const field of fields) {
    const value =
      field instanceof Uint8Array
        ? Buffer.from(field)
        : Buffer.from(String(field));
    const length = Buffer.allocUnsafe(4);
    length.writeUInt32BE(value.length);
    pieces.push(length, value);
  }
  return Buffer.concat(pieces);
}

function tag(
  secret: Uint8Array,
  fields: readonly AuthenticationField[]
): Buffer {
  return createHmac("sha256", secret).update(authEncoding(fields)).digest();
}

function framed(value: JsonObject): Buffer {
  const body = Buffer.from(JSON.stringify(value));
  if (body.length < 2 || body.length > MAX_FRAME_BYTES)
    throw frameLengthFailure("request-write");
  const header = Buffer.allocUnsafe(4);
  header.writeUInt32BE(body.length);
  return Buffer.concat([header, body]);
}

function validateTiming(
  timing: unknown,
  streaming = false
): asserts timing is RequestTimingPolicy | StreamTimingPolicy {
  const keys = [
    "connect",
    "challenge",
    "requestWrite",
    "response",
    ...(streaming ? ["stream", "end"] : []),
  ];
  if (!exactObject(timing, keys)) throw new TypeError("invalid timing policy");
  for (const policy of Object.values(timing)) {
    if (
      !exactObject(policy, ["kind", "at"]) &&
      !exactObject(policy, ["kind", "timeoutMs"])
    ) {
      throw new TypeError("invalid timing policy");
    }
    if (
      policy.kind === "absolute" &&
      typeof policy.at === "number" &&
      Number.isFinite(policy.at)
    )
      continue;
    if (
      (policy.kind === "no-progress" || policy.kind === "phase") &&
      typeof policy.timeoutMs === "number" &&
      Number.isFinite(policy.timeoutMs) &&
      policy.timeoutMs > 0
    )
      continue;
    throw new TypeError("invalid timing policy");
  }
}

type ValidatedInput = Omit<BridgeProtocolRequest, "endpoint"> & {
  endpoint: unknown;
};
type ValidatedStreamInput = Omit<StreamRequest, "endpoint"> & {
  endpoint: unknown;
};

function validateInput(
  options: unknown,
  streaming = false
): asserts options is ValidatedInput | ValidatedStreamInput {
  if (options === null || typeof options !== "object")
    throw new TypeError("request options are required");
  const candidate = options as Record<string, unknown>;
  if (!isCanonicalIdentity(candidate.requestId)) {
    throw new TypeError("requestId must be a canonical UUID");
  }
  if (
    typeof candidate.operation !== "string" ||
    candidate.operation.length === 0
  )
    throw new TypeError("operation is required");
  const credential = candidate.credential;
  if (credential === null || typeof credential !== "object")
    throw new TypeError("invalid credential");
  const credentialFields = credential as Record<string, unknown>;
  const credentialSecret = credentialFields.secret;
  if (
    !isCanonicalIdentity(credentialFields.id) ||
    !(credentialSecret instanceof Uint8Array) ||
    credentialSecret.byteLength !== 32
  ) {
    throw new TypeError("invalid credential");
  }
  validateTiming(candidate.timing, streaming);
  if (
    streaming &&
    candidate.kind !== "binary" &&
    candidate.kind !== "authenticated-frames"
  ) {
    throw new TypeError("invalid stream kind");
  }
  if (
    candidate.payload === null ||
    typeof candidate.payload !== "object" ||
    Array.isArray(candidate.payload)
  ) {
    throw new TypeError("payload must be a JSON object");
  }
  validateJson(candidate.payload);
  if (!(candidate.signal instanceof AbortSignal))
    throw new TypeError("signal is required");
}

function anchored(policy: TimingPolicy): TimingPolicy {
  return policy.kind === "phase"
    ? { kind: "absolute", at: Date.now() + policy.timeoutMs }
    : policy;
}

function deadlineMilliseconds(policy: TimingPolicy): number {
  return policy.kind === "absolute"
    ? Math.max(0, policy.at - Date.now())
    : policy.timeoutMs;
}

async function guarded<T>(
  operation: () => Promise<T>,
  policy: TimingPolicy,
  signal: AbortSignal,
  stage: BridgeProtocolFailureStage,
  onTimeout?: () => void
): Promise<T> {
  if (signal.aborted) throw failure("cancelled", stage, signal.reason);
  const timeout = deadlineMilliseconds(policy);
  if (timeout <= 0) throw failure("deadline", stage);
  let timer: ReturnType<typeof setTimeout> | undefined;
  let abort: (() => void) | undefined;
  const interruption = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      reject(failure("deadline", stage));
      onTimeout?.();
    }, timeout);
    abort = () => {
      reject(failure("cancelled", stage, signal.reason));
      onTimeout?.();
    };
    signal.addEventListener("abort", abort, { once: true });
  });
  try {
    return await Promise.race([operation(), interruption]);
  } finally {
    clearTimeout(timer);
    if (abort) signal.removeEventListener("abort", abort);
  }
}

function recordTestResourceMetric(name: string, bytes: number): void {
  if (process.env.PI_DICTATION_TEST_RESOURCE_METRICS !== "1") return;
  const target = globalThis as typeof globalThis & {
    __piDictationBridgeResourceMetrics?: Record<string, number>;
  };
  const metrics = (target.__piDictationBridgeResourceMetrics ??= {});
  metrics[name] = Math.max(metrics[name] ?? 0, bytes);
}

function netConnection(endpoint: BridgeEndpoint): Connection {
  const socket =
    endpoint.type === "unix"
      ? net.createConnection({ path: endpoint.path, allowHalfOpen: true })
      : net.createConnection({
          host: endpoint.host,
          port: endpoint.port,
          allowHalfOpen: true,
        });
  const readAvailable = () => {
    if (socket.readableLength === 0) return null;
    const chunk = socket.read(Math.min(MAX_FRAME_BYTES, socket.readableLength));
    if (chunk) recordTestResourceMetric("socket", chunk.length);
    return chunk;
  };
  return {
    connected: new Promise((resolve, reject) => {
      socket.once("connect", resolve);
      socket.once("error", reject);
    }),
    read() {
      const available = readAvailable();
      if (available) return Promise.resolve(Buffer.from(available));
      if (socket.readableEnded) return Promise.resolve(null);
      return new Promise((resolve, reject) => {
        const cleanup = () => {
          socket.removeListener("readable", readable);
          socket.removeListener("end", ended);
          socket.removeListener("close", ended);
          socket.removeListener("error", failed);
        };
        const readable = () => {
          const chunk = readAvailable();
          if (chunk === null && !socket.readableEnded) {
            socket.once("readable", readable);
            return;
          }
          cleanup();
          resolve(chunk === null ? null : Buffer.from(chunk));
        };
        const ended = () => {
          cleanup();
          resolve(null);
        };
        const failed = (error: Error) => {
          cleanup();
          reject(error);
        };
        socket.once("readable", readable);
        socket.once("end", ended);
        socket.once("close", ended);
        socket.once("error", failed);
      });
    },
    write(bytes: Uint8Array) {
      return new Promise<void>((resolve, reject) =>
        socket.write(bytes, (error) => (error ? reject(error) : resolve()))
      );
    },
    end() {
      socket.end();
    },
    destroy(error?: Error) {
      socket.destroy(error);
    },
  };
}

type TestConnectionAdapter = { connect(): Connection };

function connectionFor(endpoint: unknown): Connection {
  if (endpoint !== null && typeof endpoint === "object") {
    const adapter = (endpoint as Record<PropertyKey, unknown>)[TEST_ADAPTER];
    if (
      adapter !== null &&
      typeof adapter === "object" &&
      typeof (adapter as Partial<TestConnectionAdapter>).connect === "function"
    ) {
      return (adapter as TestConnectionAdapter).connect();
    }
  }
  if (
    endpoint === null ||
    typeof endpoint !== "object" ||
    (!(
      "type" in endpoint &&
      endpoint.type === "unix" &&
      "path" in endpoint &&
      typeof endpoint.path === "string"
    ) &&
      !(
        "type" in endpoint &&
        endpoint.type === "tcp" &&
        "host" in endpoint &&
        typeof endpoint.host === "string" &&
        "port" in endpoint &&
        typeof endpoint.port === "number" &&
        Number.isInteger(endpoint.port) &&
        endpoint.port >= 1 &&
        endpoint.port <= 65_535
      ))
  ) {
    throw new TypeError("invalid endpoint");
  }
  return netConnection(endpoint as BridgeEndpoint);
}

interface Connection {
  connected: Promise<void>;
  read(): Promise<Buffer | null>;
  write(bytes: Uint8Array): Promise<void>;
  end(): void;
  destroy(error?: Error): void;
}

class StreamGuard {
  policy: TimingPolicy;
  signal: AbortSignal;
  connection: Connection;
  interruption: Promise<never>;
  reject!: (error: unknown) => void;
  abort: () => void;
  timer: ReturnType<typeof setTimeout> | undefined;
  interrupted: unknown;

  constructor(
    policy: TimingPolicy,
    signal: AbortSignal,
    connection: Connection
  ) {
    this.policy = policy;
    this.signal = signal;
    this.connection = connection;
    this.interruption = new Promise((_, reject) => {
      this.reject = reject;
    });
    this.abort = () =>
      this.interrupt(failure("cancelled", "stream", signal.reason));
    signal.addEventListener("abort", this.abort, { once: true });
    this.arm();
    if (signal.aborted) this.abort();
  }

  arm() {
    clearTimeout(this.timer);
    const timeout = deadlineMilliseconds(this.policy);
    if (timeout <= 0) {
      this.interrupt(failure("deadline", "stream"));
      return;
    }
    this.timer = setTimeout(
      () => this.interrupt(failure("deadline", "stream")),
      timeout
    );
  }

  interrupt(error: unknown): void {
    if (this.interrupted) return;
    this.interrupted = error;
    this.reject(error);
  }

  check(): void {
    if (this.interrupted) throw this.interrupted;
    if (this.signal.aborted) {
      this.interrupt(failure("cancelled", "stream", this.signal.reason));
      throw this.interrupted;
    }
    if (this.policy.kind === "absolute" && this.policy.at <= Date.now()) {
      this.interrupt(failure("deadline", "stream"));
      throw this.interrupted;
    }
  }

  progress(): void {
    this.check();
    if (this.policy.kind === "no-progress") this.arm();
  }

  async race<T>(operation: () => Promise<T>): Promise<T> {
    if (this.interrupted) return this.interruption;
    try {
      this.check();
    } catch {
      return this.interruption;
    }
    return Promise.race([operation(), this.interruption]);
  }

  close(): void {
    clearTimeout(this.timer);
    this.signal.removeEventListener("abort", this.abort);
  }
}

class Reader {
  connection: Connection;
  signal: AbortSignal;
  policy: TimingPolicy;
  stage: BridgeProtocolFailureStage;
  buffer: Buffer;
  guard: StreamGuard | undefined;

  constructor(
    connection: Connection,
    signal: AbortSignal,
    policy: TimingPolicy,
    stage: BridgeProtocolFailureStage
  ) {
    this.connection = connection;
    this.signal = signal;
    this.policy = anchored(policy);
    this.stage = stage;
    this.buffer = Buffer.alloc(0);
    this.guard = undefined;
  }

  async chunk(): Promise<Buffer | null> {
    try {
      const chunk = this.guard
        ? await this.guard.race(() => this.connection.read())
        : await guarded(
            () => this.connection.read(),
            this.policy,
            this.signal,
            this.stage,
            () => this.connection.destroy()
          );
      if (chunk !== null) this.guard?.progress();
      return chunk;
    } catch (error) {
      if (error instanceof BridgeProtocolFailure) throw error;
      throw failure("transport", this.stage, error);
    }
  }

  async exactly(length: number): Promise<Buffer> {
    this.guard?.check();
    const pieces = [];
    let total = 0;
    if (this.buffer.length > 0) {
      pieces.push(this.buffer.subarray(0, length));
      total = Math.min(length, this.buffer.length);
      this.buffer = this.buffer.subarray(total);
      if (total > 0) this.guard?.progress();
    }
    while (total < length) {
      const chunk = await this.chunk();
      if (chunk === null)
        throw failure("transport", this.stage, new Error("unexpected EOF"));
      const needed = length - total;
      pieces.push(chunk.subarray(0, needed));
      total += Math.min(needed, chunk.length);
      if (chunk.length > needed) this.buffer = chunk.subarray(needed);
    }
    return Buffer.concat(pieces, length);
  }

  async frame(): Promise<JsonValue> {
    const header = await this.exactly(4);
    const length = header.readUInt32BE(0);
    if (length < 2 || length > MAX_FRAME_BYTES)
      throw frameLengthFailure(this.stage);
    return strictJson(await this.exactly(length), this.stage);
  }

  async end(): Promise<void> {
    if (this.policy.kind === "absolute" && this.policy.at <= Date.now())
      throw failure("deadline", this.stage);
    if (this.buffer.length > 0) throw trailingBytesFailure(this.stage);
    const trailing = await this.chunk();
    if (trailing !== null) throw trailingBytesFailure(this.stage);
  }
}

async function openAuthenticated(options: unknown, streaming = false) {
  let payloadBytes;
  try {
    validateInput(options, streaming);
    payloadBytes = Buffer.from(JSON.stringify(options.payload));
  } catch (error) {
    throw failure("malformed", "request-write", error);
  }
  const { endpoint, credential, requestId, operation, timing, signal } =
    options;
  if (signal.aborted) throw failure("cancelled", "connect", signal.reason);
  if (timing.connect.kind === "absolute" && timing.connect.at <= Date.now()) {
    throw failure("deadline", "connect");
  }
  let connection;
  try {
    connection = connectionFor(endpoint);
  } catch (error) {
    if (error instanceof TypeError)
      throw failure("malformed", "connect", error);
    throw failure("transport", "connect", error);
  }
  try {
    try {
      await guarded(
        () => connection.connected,
        anchored(timing.connect),
        signal,
        "connect",
        () => connection.destroy()
      );
    } catch (error) {
      if (error instanceof BridgeProtocolFailure) throw error;
      throw failure("transport", "connect", error);
    }
    const challengeReader = new Reader(
      connection,
      signal,
      timing.challenge,
      "challenge"
    );
    const challengeMessage = await challengeReader.frame();
    if (challengeReader.buffer.length > 0)
      throw trailingBytesFailure("challenge");
    if (
      !exactObject(challengeMessage, ["type", "challenge"]) ||
      challengeMessage.type !== "challenge"
    ) {
      throw failure("malformed", "challenge");
    }
    const challenge = canonicalBase64(
      challengeMessage.challenge,
      32,
      "challenge"
    );
    const secret = Buffer.from(credential.secret);
    const requestTag = tag(secret, [
      "request",
      protocolVersion,
      challenge,
      credential.id,
      requestId,
      operation,
      payloadBytes,
    ]);
    const bytes = framed({
      type: "request",
      version: protocolVersion,
      credentialId: credential.id,
      requestId,
      operation,
      payload: payloadBytes.toString("base64"),
      hmac: requestTag.toString("hex"),
    });
    try {
      await guarded(
        () => connection.write(bytes),
        anchored(timing.requestWrite),
        signal,
        "request-write",
        () => connection.destroy()
      );
      connection.end();
    } catch (error) {
      if (error instanceof BridgeProtocolFailure) throw error;
      throw failure("transport", "request-write", error);
    }
    const reader = new Reader(connection, signal, timing.response, "response");
    const response = await reader.frame();
    if (
      !exactObject(response, [
        "type",
        "version",
        "requestId",
        "status",
        "payload",
        "hmac",
      ]) ||
      response.type !== "response" ||
      typeof response.version !== "number" ||
      !Number.isSafeInteger(response.version) ||
      response.version < 1 ||
      response.requestId !== requestId ||
      typeof response.status !== "string" ||
      !STATUSES.has(response.status) ||
      typeof response.payload !== "string"
    ) {
      throw failure("malformed", "response");
    }
    const responsePayload = canonicalBase64(response.payload);
    const expected = tag(secret, [
      "response",
      protocolVersion,
      response.version,
      challenge,
      credential.id,
      requestId,
      `${operation}:${response.status}`,
      responsePayload,
    ]);
    const actual = canonicalHex(response.hmac, expected.length);
    if (!timingSafeEqual(actual, expected))
      throw failure("authentication", "response");
    let parsed;
    try {
      parsed = strictJson(responsePayload);
    } catch (error) {
      throw payloadFailure(
        "response",
        error instanceof Error ? error.cause : error
      );
    }
    if (response.status === "version-mismatch") {
      if (
        !exactObject(parsed, ["clientVersion", "companionVersion"]) ||
        parsed.clientVersion !== protocolVersion ||
        parsed.companionVersion !== response.version ||
        response.version === protocolVersion
      )
        throw versionDataFailure("response");
    } else if (response.version !== protocolVersion)
      throw versionDataFailure("response");
    return {
      connection,
      reader,
      challenge,
      secret,
      status: response.status as BridgeProtocolStatus,
      payload: parsed,
    };
  } catch (error) {
    connection.destroy();
    throw error;
  }
}

class BinaryByteSource {
  reader: Reader;
  incomplete: boolean;

  constructor(reader: Reader) {
    this.reader = reader;
    this.incomplete = false;
  }

  readExactly(length: number): AsyncIterable<Uint8Array> {
    if (!Number.isSafeInteger(length) || length < 0)
      throw new TypeError("length must be a non-negative safe integer");
    if (this.incomplete) throw new TypeError("an exact read is already active");
    this.incomplete = true;
    let remaining = length;
    const source = this;
    return (async function* () {
      try {
        while (remaining > 0) {
          const chunk = await source.reader.exactly(
            Math.min(MAX_FRAME_BYTES, remaining)
          );
          remaining -= chunk.length;
          yield chunk;
        }
      } finally {
        if (remaining === 0) source.incomplete = false;
      }
    })();
  }

  verifyComplete(): void {
    if (this.incomplete) throw failure("malformed", "stream");
  }
}

class AuthenticatedFrameSource implements AsyncIterable<JsonValue> {
  reader: Reader;
  secret: Buffer;
  challenge: Buffer;
  credentialId: string;
  requestId: string;
  iterated: boolean;

  constructor(
    reader: Reader,
    secret: Buffer,
    challenge: Buffer,
    credentialId: string,
    requestId: string
  ) {
    this.reader = reader;
    this.secret = secret;
    this.challenge = challenge;
    this.credentialId = credentialId;
    this.requestId = requestId;
    this.iterated = false;
  }

  [Symbol.asyncIterator]() {
    if (this.iterated)
      throw new TypeError("authenticated frames can only be iterated once");
    this.iterated = true;
    let sequence = 0;
    return {
      next: async () => {
        const message = await this.reader.frame();
        if (
          !exactObject(message, [
            "type",
            "version",
            "requestId",
            "streamSequence",
            "payload",
            "hmac",
          ]) ||
          message.type !== "level-event" ||
          message.version !== protocolVersion ||
          message.requestId !== this.requestId ||
          message.streamSequence !== sequence ||
          typeof message.payload !== "string" ||
          typeof message.hmac !== "string"
        ) {
          throw failure("malformed", "stream");
        }
        const payload = canonicalBase64(message.payload, undefined, "stream");
        const expected = tag(this.secret, [
          "stream",
          protocolVersion,
          message.version,
          this.challenge,
          this.credentialId,
          this.requestId,
          sequence,
          payload,
        ]);
        const actual = canonicalHex(message.hmac, expected.length, "stream");
        if (!timingSafeEqual(actual, expected))
          throw failure("authentication", "stream");
        sequence += 1;
        return { done: false, value: strictJson(payload, "stream") };
      },
    };
  }
}

export async function request(
  options: BridgeProtocolRequest
): Promise<BridgeProtocolResponse> {
  const opened = await openAuthenticated(options);
  try {
    await opened.reader.end();
    return { status: opened.status, payload: opened.payload };
  } finally {
    opened.connection.destroy();
  }
}

export async function withStream<T>(
  options: BinaryStreamRequest,
  consumer: (context: BinaryStreamContext) => T | Promise<T>
): Promise<BridgeProtocolStreamResponse<T>>;
export async function withStream<T>(
  options: AuthenticatedFrameStreamRequest,
  consumer: (context: AuthenticatedFrameStreamContext) => T | Promise<T>
): Promise<BridgeProtocolStreamResponse<T>>;
export async function withStream<T>(
  options: StreamRequest,
  consumer: (context: never) => T | Promise<T>
): Promise<BridgeProtocolStreamResponse<T>> {
  if (typeof consumer !== "function")
    throw failure(
      "malformed",
      "request-write",
      new TypeError("consumer is required")
    );
  const opened = await openAuthenticated(options, true);
  const { connection, reader, challenge, secret, status, payload } = opened;
  try {
    if (status !== "ok") {
      reader.policy = anchored(options.timing.end);
      reader.stage = "stream";
      await reader.end();
      return { status, payload };
    }
    const guard = new StreamGuard(
      anchored(options.timing.stream),
      options.signal,
      connection
    );
    reader.guard = guard;
    reader.stage = "stream";
    let source;
    const context =
      options.kind === "binary"
        ? { metadata: payload, bytes: (source = new BinaryByteSource(reader)) }
        : {
            metadata: payload,
            frames: new AuthenticatedFrameSource(
              reader,
              secret,
              challenge,
              options.credential.id,
              options.requestId
            ),
          };
    let value;
    try {
      value = await guard.race(() =>
        Promise.resolve().then(() => consumer(context as never))
      );
    } finally {
      guard.close();
      reader.guard = undefined;
    }
    if (source) {
      source.verifyComplete();
      reader.policy = anchored(options.timing.end);
      await reader.end();
    }
    return { status, payload, value };
  } finally {
    connection.destroy();
  }
}
